services:
  fastapi_app:
    container_name: fastapi_app
    build: .
    #volumes:
    #  - ./app:/app
    volumes:
      - ./cert:/app/backend/cert
    ports:
      - 3001:3001
    environment:
      - WATSONX_URL=https://us-south.ml.cloud.ibm.com
      - WX_PROJECT_ID=<Watsonx Project ID>
      - IBM_CLOUD_API_KEY=<IBM Cloud API Key>
      - LLM_JUDGE_API_KEY=JudgeIt-Secret-Api-Key
      - WX_PLATFORM=saas
      - WX_USER=''
      - WX_GOV_REGION=eu-de
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - SERVER_URL=http://localhost:3001
      - MONGO_URL=<MONGO URL>
      - MONGO_USER=<MONGO USER>
      - MONGO_PASS=<MONGO PASS>
      - MONGO_DB=<MONGO DB>
    restart: always

  redis:
    container_name: redis
    image: redis:7.2.5-alpine
    restart: always

  celery_worker:
    container_name: celery_worker
    build: .
    #volumes:
    #  - ./app:/app
    command: celery -A app.celery.celery_worker.celery worker --loglevel=info
    environment:
      - WATSONX_URL=https://us-south.ml.cloud.ibm.com
      - WX_PROJECT_ID=<watsonx Project ID>
      - WX_PLATFORM=saas
      - WX_USER=''
      - WX_GOV_REGION=eu-de
      - IBM_CLOUD_API_KEY=<watsonx cloud api key>
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - fastapi_app
      - redis
    restart: always

  flower:
    container_name: flower
    build: .
    command: celery --broker=redis://redis:6379/0 flower --port=5555
    ports:
      - 5556:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - fastapi_app
      - redis
      - celery_worker
    restart: always
