apiVersion: v1
kind: Service
metadata:
  name: fastapi-app
  labels:
    app: fastapi-app
spec:
  type: {{ .Values.service.fastapi.type }}
  ports:
    - port: {{ .Values.service.fastapi.port }}
      targetPort: {{ .Values.service.fastapi.port }}
  selector:
    app: fastapi-app

---

apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  type: {{ .Values.service.redis.type }}
  ports:
    - port: {{ .Values.service.redis.port }}
      targetPort: {{ .Values.service.redis.port }}
  selector:
    app: redis

---

apiVersion: v1
kind: Service
metadata:
  name: flower
  labels:
    app: flower
spec:
  type: {{ .Values.service.flower.type }}
  ports:
    - port: {{ .Values.service.flower.port }}
      targetPort: {{ .Values.service.flower.port }}
  selector:
    app: flower
